#pragma once

#include "quantum.h"

enum my_keycodes {
    INDICATOR_HUEU = SAFE_RANGE,
    INDICATOR_HUED,
    INDICATOR_SPDU,
    INDICATOR_SPDD,
    INDICATOR_VALU,
    INDICATOR_VALD,
    INDICATOR_MODE,
    INDICATOR_CHRG,
    BATTERY_LEVEL,

    ID_HUEU = INDICATOR_HUEU,
    ID_HUED = INDICATOR_HUED,
    ID_SPDU = INDICATOR_SPDU,
    ID_SPDD = INDICATOR_SPDD,
    ID_VALU = INDICATOR_VALU,
    ID_VALD = INDICATOR_VALD,
    ID_MODE = INDICATOR_MODE,
    ID_CHRG = INDICATOR_CHRG,
    BAT_LVL = BATTERY_LEVEL
};
